### ISSUE TITLE
你好,关于你用到的rtsp组件。有个问题想请教你

### ISSUE THREAD

**Issue by mythbobo** [ChenArno/tianjiApp#1]
你好,无意中搜索到你的代码中有使用到rtsp播放器。。我下载了你的代码，将这个组件移植到我的项目中。报了一个错误。调试两天了，都不知道是什么原因。能否帮忙看一下呢？因为weex的rtsp播放器功能只有你这儿有。如果有时间。。不知道能否开源成插件形式?万分感谢！

11-26 13:58:54.777 14338-14338/? E/SharedSettings: SharedSettings: Load settings.
11-26 13:58:54.784 14338-14338/? E/SharedSettings: SharedSettings: Load settings.
11-26 13:58:54.784 14338-14492/? E/zygote: No implementation found for long veg.mediaplayer.sdk.MediaPlayer.nativePlayerInit(long[], veg.mediaplayer.sdk.MediaPlayer) (tried Java_veg_mediaplayer_sdk_MediaPlayer_nativePlayerInit and Java_veg_mediaplayer_sdk_MediaPlayer_nativePlayerInit___3JLveg_mediaplayer_sdk_MediaPlayer_2)
11-26 13:58:54.784 14338-14338/? E/SharedSettings: SharedSettings: Load settings.
11-26 13:58:54.785 14338-14492/? E/AndroidRuntime: FATAL EXCEPTION: MediaPlayerThread
                                                   Process: com.benmu.wx, PID: 14338
                                                   java.lang.UnsatisfiedLinkError: No implementation found for long veg.mediaplayer.sdk.MediaPlayer.nativePlayerInit(long[], veg.mediaplayer.sdk.MediaPlayer) (tried Java_veg_mediaplayer_sdk_MediaPlayer_nativePlayerInit and Java_veg_mediaplayer_sdk_MediaPlayer_nativePlayerInit___3JLveg_mediaplayer_sdk_MediaPlayer_2)
                                                       at veg.mediaplayer.sdk.MediaPlayer.nativePlayerInit(Native Method)
                                                       at veg.mediaplayer.sdk.MediaPlayerWorker.run(MediaPlayer.java:4051)
                                                       at java.lang.Thread.run(Thread.java:764)
11-26 13:58:54.858 3491-3583/? E/PhoneWindow_APM :: sendNotificationForAppPermissionMonitor callingPid = 3491, uid = 1000
11-26 13:58:54.858 3491-3583/? E/PhoneWindow_APM :: sendNotificationForAppPermissionMonitor 2
11-26 13:58:54.858 3491-3583/? E/PhoneWindow_APM :: sendNotificationForAppPermissionMonitor 21000_3491
11-26 13:58:54.858 3491-3583/? E/PhoneWindow_APM :: isCalledPackage return true
11-26 13:58:54.891 14338-14497/? E/zygote: No implementation found for long veg.mediaplayer.sdk.MediaPlayer.nativePlayerInit(long[], veg.mediaplayer.sdk.MediaPlayer) (tried Java_veg_mediaplayer_sdk_MediaPlayer_nativePlayerInit and Java_veg_mediaplayer_sdk_MediaPlayer_nativePlayerInit___3JLveg_mediaplayer_sdk_MediaPlayer_2)

**Comment by mythbobo** [comment]
今天我打包了apk文件。改成zip后发现一个问题。为什么libs目录下只有armeabi和x86,而mediaplayersdk.jar没有被打包进来。。不知道是否是此原因导致报错？

**Comment by mythbobo** [comment]
还有为什么ios用vlc,android不用呢?

**Comment by mythbobo** [comment]
@ChenArno 大神能回复我一下么

**Comment by ChenArno** [comment]
额，我现在才看到，当年我用的是github上的android开源插件，通过插件方式引入的，具体做法跟官方一样，现在我没去用weex了，
